Issue/revaluate intentions
Ulises961/Deliveroo-project pull request #13
Opened 2024-04-27 13:25 UTC by DeeJack

Now the agent is able to revaluate the intentions as he goes, so if a parcel appears while he's delivering, he can choose to pick it up.

A reachableCells array has been added. It's a boolean matrix that has true in the position of cells that are reachable for the agent. The array is computed the first time the onYou event is called, and it is computed only once.

2024-04-27 15:18 UTC, Ulises961 requested changes
Method signatures need review
Removal of impossible actions from the queue improves the efficiency of the agent, and the iteration over its queue of intentions

2024-04-27 15:18 UTC, Ulises961 commented on src/lib/agents/Agent.js
Why is the sort intentions async? and then all the chain of asynchronous functions? The properties we use to manipulate the Intention are not related to the Promise object that the Intention extends. So this can be safely done in a synchronous way without needing to add further complexity to the code

2024-04-27 15:18 UTC, Ulises961 commented on src/lib/plans/FollowPath.js
Let us remove commented or unused code to keep the working space clean

2024-04-27 15:18 UTC, Ulises961 commented on src/lib/plans/GoPickUp.js
The marking for deletion of the pick up intention is critical to avoid keeping an impossible action in the queue of actions

2024-04-27 15:18 UTC, Ulises961 commented on src/lib/plans/other/AgentLoop.js
There is an over complication of the method signatures which is unnecessary.

2024-04-27 15:40 UTC, DeeJack commented on src/lib/agents/Agent.js
That's for when I was trying to fix the parcel sensing, that was not actually necessary.
Technically, we COULD revert those functions to be synchronous, but should we? Everything in this program should be async, so that nothing is blocked.

2024-04-27 15:40 UTC, DeeJack commented on src/lib/plans/FollowPath.js
We should.

2024-04-27 15:42 UTC, DeeJack commented on src/lib/plans/GoPickUp.js
I already reverted this change in commit [85fb594](https://github.com/Ulises961/Deliveroo-project/pull/13/commits/85fb594f685d36ebac9d5c801bdc2a9df66a576f).

2024-04-27 15:43 UTC, DeeJack commented on src/lib/plans/other/AgentLoop.js
Maybe. I think that every "hard to compute" method should be async.
And adding async doesn't add that much complexity.

2024-04-27 15:44 UTC, DeeJack reviewed
I feel like the requested changes are not relevant.

2024-04-27 15:53 UTC, Ulises961 commented on src/lib/agents/Agent.js
I think we should. The changes do not add any functionality and create a chain of async for functions calling them. If we do not require async code it simplifies the logic we are producing and makes our life easier in the end

2024-04-27 15:57 UTC, DeeJack commented on src/lib/agents/Agent.js
I agree that the methods we have are very complex.
I do not agree that adding an async and an await adds that much complexity.
If you prefer, you can remove them. If the program still works as expectedd, then I'm okay with it.

2024-04-28 10:10 UTC, Ulises961 approved these changes

2024-04-28 10:11 UTC, merged